language: python

python:
  - 2.7

env:
  - TEST_DATABASE_URL=postgres://postgres@localhost/talkoohakemisto_test

before_install:
  - sudo apt-get install -y libevent-dev

install:
  - pip install -r requirements-dev.txt

before_script:
  - psql -c 'create database talkoohakemisto_test;' -U postgres
  - psql -c 'create database talkoohakemisto_test2;' -U postgres

script:
  - py.test -n 2
