"""Added column picture_url to voluntary_works

Revision ID: 109e4fc326be
Revises: 32879aefe27a
Create Date: 2014-08-21 14:05:16.316379

"""

# revision identifiers, used by Alembic.
revision = '109e4fc326be'
down_revision = '32879aefe27a'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voluntary_work', sa.Column('picture_url', sa.Unicode(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voluntary_work', 'picture_url')
    ### end Alembic commands ###
